- MaxDistDataPointsFilter:
    maxDist:       50.0
- RandomSamplingDataPointsFilter:
    prob:          0.65
- SurfaceNormalDataPointsFilter:
    knn:           20
    epsilon:       3.15
    keepNormals:   1
    keepDensities: 1
