- FixStepSamplingDataPointsFilter:
    startStep:     13
- BoundingBoxDataPointsFilter:
    xMin:          -inf
    xMax:          inf
    yMin:          -inf
    yMax:          inf
    zMin:          -inf
    zMax:          inf
    removeInside:  0
- MaxDistDataPointsFilter:
    maxDist:       50.0
- RandomSamplingDataPointsFilter:
    prob:          0.3
- SurfaceNormalDataPointsFilter:
    knn:           15
    epsilon:       1.66
    keepNormals:   1
    keepDensities: 1
- MaxDensityDataPointsFilter:
    maxDensity:    50.0
- SimpleSensorNoiseDataPointsFilter:
    sensorType:    0
