readingDataPointsFilters:
  - SamplingSurfaceNormalDataPointsFilter:
      knn:                   20
      keepDensities:         1
  - RemoveNaNDataPointsFilter:

referenceDataPointsFilters:
  - MaxDistDataPointsFilter:
      maxDist:               50.0
  - SamplingSurfaceNormalDataPointsFilter:
      knn:                   20
      keepDensities:         1

matcher:
  KDTreeMatcher:
    knn:                     1
    epsilon:                 0

outlierFilters:
  - TrimmedDistOutlierFilter:
     ratio:                  0.6

errorMinimizer:
  PointToPlaneWithCovErrorMinimizer

transformationCheckers:
  - DifferentialTransformationChecker:
      minDiffRotErr:         0.0001
      minDiffTransErr:       0.00001
      smoothLength:          4
  - CounterTransformationChecker:
      maxIterationCount:     200

inspector:
#  VTKFileInspector:
#    dumpDataLinks:          1
#    dumpReading:            1
#    dumpReference:          1
  NullInspector

logger:
#  FileLogger
  NullLogger
