readingDataPointsFilters:
  - SurfaceNormalDataPointsFilter:
        knn:                 20
        keepDensities:       1
        keepNormals:         1
  - MaxDensityDataPointsFilter:
       maxDensity:           50

referenceDataPointsFilters:
  - SurfaceNormalDataPointsFilter:
      knn:                   20
      keepDensities:         1
      keepNormals:           1
  - RandomSamplingDataPointsFilter:
      prob:                  0.50

matcher:
  KDTreeMatcher:
    knn:                     1
    epsilon:                 3.16

outlierFilters:
  - TrimmedDistOutlierFilter:
      ratio:                 0.358818

errorMinimizer:
  PointToPlaneErrorMinimizer

transformationCheckers:
  - CounterTransformationChecker:
      maxIterationCount:     100
  - DifferentialTransformationChecker:
      minDiffRotErr:         0.0001
      minDiffTransErr:       0.0001
      smoothLength:          4

inspector:
  PerformanceInspector
#  VTKFileInspector
#     baseFileName :         vissteps
#     dumpReading :          1
#     dumpReference :        1
#     dumpDataLinks :        1

logger:
  NullLogger
#  FileLogger
