sensors:
  - id:                                    3da6d03bd42e41a93dc941bd5fd9353d
    sensor_type:                           IMU
    description:                           "Bosch BMI085 IMU"
    topic:                                 /alphasense/imu
    sigmas:
      acc_bias_random_walk_noise_density:  0.0043
      acc_noise_density:                   0.019
      gyro_bias_random_walk_noise_density: 0.000266
      gyro_noise_density:                  0.019
    saturation_accel_max_mps2:             150
    saturation_gyro_max_radps:             7.5
    gravity_magnitude_mps2:                9.808083883386614


  - id:                                    bbf123479caf7592b35518478a2fe08d
    sensor_type:                           LIDAR
    description:                           "Lidarmace - Ouster OS0"
    topic:                                 /os_cloud_node/points

  - id:                                    acbb23479caf7592b35518478a2fe08f
    sensor_type:                           ODOMETRY_6DOF
    description:                           "OKVIS"
    topic:                                 /odometry/maplab_odom_T_M_I
    T_St_Stp1_fixed_covariance:
      rows: 6
      cols: 6
      data:
        - [0.001, 0.0,  0.0,  0.0,   0.0,   0.0]
        - [0.0,  0.001, 0.0,  0.0,   0.0,   0.0]
        - [0.0,  0.0,  0.001, 0.0,   0.0,   0.0]
        - [0.0,  0.0,  0.0,   0.05,  0.0,   0.0]
        - [0.0,  0.0,  0.0,   0.0,   0.05,  0.0]
        - [0.0,  0.0,  0.0,   0.0,   0.0,  0.05]

  - id:                                    4af1bac2a7c5fad79f09e49e3b96d87c
    sensor_type:                           NCAMERA
    description:                           "Alphasense"
    topic:                                 ""
    cameras:
      - camera:
          id:                              9da9c2fa16894a059f8b40740c721cb1
          sensor_type:                     CAMERA
          description:                     "Forward Up"
          topic:                           /alphasense/cam0
          line-delay-nanoseconds:          0
          image_height:                    1080
          image_width:                     1440
          type:                            pinhole
          intrinsics:
            rows:                          4
            cols:                          1
            data:
              - 701.6682111281
              - 701.55526909
              - 703.6097253263
              - 530.4665279367
          distortion:
            type:                          equidistant
            parameters:
              rows:                        4
              cols:                        1
              data:
                - -0.0395909069
                - -0.0041727433
                - 0.0030288415
                - -0.0012784168
        T_B_C:
          rows:                            4
          cols:                            4
          data:
            - [-0.002821475675, -0.003074758359, 0.999991292530, 0.05067834857850693]
            - [-0.999995472623, -0.001037272511, -0.002824676859, 0.0458784339890185]
            - [0.001045948678, -0.999994734950, -0.003071817799, -0.005943648304780761]
            - [0.0, 0.0, 0.0, 1.0]

      - camera:
          id:                              44ed7e1913a847b3b8d9884b9b02fb03
          sensor_type:                     CAMERA
          description:                     "Forward Down"
          topic:                           /alphasense/cam1
          line-delay-nanoseconds:          0
          image_height:                    1080
          image_width:                     1440
          type:                            pinhole
          intrinsics:
            rows:                          4
            cols:                          1
            data:
              - 696.7174426776
              - 696.4862496732
              - 708.4206218964
              - 535.6712007522
          distortion:
            type:                          equidistant
            parameters:
              rows:                        4
              cols:                        1
              data:
                - -0.0465180371
                - 0.0160363324
                - -0.0170339468
                - 0.0050095489
        T_B_C:
          rows:                            4
          cols:                            4
          data:
            - [-0.002731256802, 0.001246716447, 0.999995492957, 0.0507054642910155]
            - [0.999990530035, 0.003391641318, 0.002727014813, -0.060959522169800155]
            - [-0.003388226217, 0.999993471212, -0.001255968084, -0.005930631162279414]
            - [0.0, 0.0, 0.0, 1.0]


      - camera:
          id:                              08faa68c87a84fd5bd1b0305c99b155d
          sensor_type:                     CAMERA
          description:                     "Upwards"
          topic:                           /alphasense/cam2
          line-delay-nanoseconds:          0
          image_height:                    1080
          image_width:                     1440
          type:                            pinhole
          intrinsics:
            rows:                          4
            cols:                          1
            data:
              - 702.3538912351
              - 702.1759854802
              - 718.7749348353
              - 535.2856167618
          distortion:
            type:                          equidistant
            parameters:
              rows:                        4
              cols:                        1
              data:
                - -0.0392852639
                - -0.0023244164
                - -0.0005553017
                - 0.0002238156
        T_B_C:
          rows:                            4
          cols:                            4
          data:
            - [-0.999921221136, -0.007223717976, -0.010264960828, 0.0066556070130705325]
            - [-0.007244879819, 0.999971703377, 0.002025872901, -0.007297504322474243]
            - [0.010250036030, 0.002100081712, -0.999945261711, -0.035615803708099754]
            - [0.0, 0.0, 0.0, 1.0]

      - camera:
          id:                              da7d19d6662f4a428240bf7f706bbb4d
          sensor_type:                     CAMERA
          description:                     "Right"
          topic:                           /alphasense/cam3
          line-delay-nanoseconds:          0
          image_height:                    1080
          image_width:                     1440
          type:                            pinhole
          intrinsics:
            rows:                          4
            cols:                          1
            data:
              - 703.2325755934
              - 703.2405654818
              - 703.0078028901
              - 537.7049174331
          distortion:
            type:                          equidistant
            parameters:
              rows:                        4
              cols:                        1
              data:
                - -0.041473724
                - 0.000366189
                - -0.0008241712
                - -0.0002216933
        T_B_C:
          rows:                            4
          cols:                            4
          data:
            - [0.999996177549, -0.002751862421, -0.000268591271, -0.007959549138437914]
            - [0.000262301292, -0.002285822930, 0.999997353102, 0.06467457049779392]
            - [-0.002752469089, -0.999993601113, -0.002285092375, -0.006489835360873981]
            - [0.0, 0.0, 0.0, 1.0]

      - camera:
          id:                              c70f9347314d4c26a72280c1f193b47d
          sensor_type:                     CAMERA
          description:                     "Left"
          topic:                           /alphasense/cam4
          line-delay-nanoseconds:          0
          image_height:                    1080
          image_width:                     1440
          type:                            pinhole
          intrinsics:
            rows:                          4
            cols:                          1
            data:
              - 701.4723842948
              - 701.6419154268
              - 700.4808652897
              - 541.8573746426
          distortion:
            type:                          equidistant
            parameters:
              rows:                        4
              cols:                        1
              data:
                - -0.0405675926
                - 0.0010964136
                - -0.0027765896
                - 0.0006435363
        T_B_C:
          rows:                            4
          cols:                            4
          data:
            - [0.999933871202, 0.011175514715, 0.002713133589, -0.009899820375326171]
            - [0.002673611571, 0.003549906077, -0.999990124935, -0.07835193358130926]
            - [-0.011185035725, 0.999931250656, 0.003519792340, -0.006247994340411725]
            - [0.0, 0.0, 0.0, 1.0]


extrinsics:
  - sensor_id:                             bbf123479caf7592b35518478a2fe08d
    base_sensor_id:                        3da6d03bd42e41a93dc941bd5fd9353d
    T_B_S:
      rows:                                4
      cols:                                4
      data:
        - [0.999975731551, 0.002455644467, -0.006519671776, 0.01001966915517371]
        - [0.002457854216, -0.999996924709, 0.000330944944, -0.006645473484212856]
        - [-0.006518839043, -0.000346961315, -0.999978691951, 0.09473042428051345]
        - [0, 0, 0, 1]

  - sensor_id:                             3da6d03bd42e41a93dc941bd5fd9353d
    base_sensor_id:                        3da6d03bd42e41a93dc941bd5fd9353d
    T_B_S:
      rows:                                4
      cols:                                4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]

  - sensor_id:                             acbb23479caf7592b35518478a2fe08f
    base_sensor_id:                        3da6d03bd42e41a93dc941bd5fd9353d
    T_B_S:
      rows:                                4
      cols:                                4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]

  - sensor_id:                             4af1bac2a7c5fad79f09e49e3b96d87c
    base_sensor_id:                        3da6d03bd42e41a93dc941bd5fd9353d
    T_B_S:
      rows:                                4
      cols:                                4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]
