sensors:
  - id:                                    3da6d03bd42e41a93dc941bd5fd9353d
    sensor_type:                           IMU
    description:                           "Bosch BMI085 IMU"
    topic:                                 /alphasense/imu_adis
    sigmas:
      gyro_noise_density:                  0.005
      gyro_bias_random_walk_noise_density: 4e-06
      acc_noise_density:                   0.01
      acc_bias_random_walk_noise_density:  0.0002
    saturation_accel_max_mps2:             150
    saturation_gyro_max_radps:             7.5
    gravity_magnitude_mps2:                9.808083883386614


  - id:                                    bbf123479caf7592b35518478a2fe08d
    sensor_type:                           LIDAR
    description:                           "Lidarmace - Ouster OS0"
    topic:                                 /os_cloud_node/points

  - id:                                    acbb23479caf7592b35518478a2fe08f
    sensor_type:                           ODOMETRY_6DOF
    description:                           "OKVIS"
    topic:                                 /odometry/maplab_odom_T_M_I


    #T_St_Stp1_fixed_covariance:
    #  rows: 6
    #  cols: 6
    #  data:
    #    - [0.01, 0.0,  0.0,   0.0,  0.0,  0.0]
    #    - [0.0,  0.01, 0.0,   0.0,  0.0,  0.0]
    #    - [0.0,  0.0,  0.01,  0.0,  0.0,  0.0]
    #    - [0.0,  0.0,  0.0,   0.1,  0.0,  0.0]
    #    - [0.0,  0.0,  0.0,   0.0,  0.1,  0.0]
    #    - [0.0,  0.0,  0.0,   0.0,  0.0,  0.1]

  - id:                                    4af1bac2a7c5fad79f09e49e3b96d87c
    sensor_type:                           NCAMERA
    description:                           "Alphasense"
    topic:                                 ""
    cameras:
      - camera:
          id:                              9da9c2fa16894a059f8b40740c721cb1
          sensor_type:                     CAMERA
          description:                     "Forward Up"
          topic:                           /alphasense/cam0
          line-delay-nanoseconds:          0
          image_height:                    1080
          image_width:                     1440
          type:                            pinhole
          intrinsics:
            rows:                          4
            cols:                          1
            data:
              - 701.6682111281
              - 701.55526909
              - 703.6097253263
              - 530.4665279367
          distortion:
            type:                          equidistant
            parameters:
              rows:                        4
              cols:                        1
              data:
                - -0.0395909069
                - -0.0041727433
                - 0.0030288415
                - -0.0012784168
        T_B_C:
          rows:                            4
          cols:                            4
          data:
            - [0.999990861752, 0.000628464640, -0.004228645702, -0.052798019321]
            - [-0.004226691177, -0.003079450931, -0.999986325938, -0.078374861539]
            - [-0.000641477954, 0.999995060995, -0.003076766464, -0.026280993585]
            - [0.000000000000, 0.000000000000, 0.000000000000, 1.000000000000]

      - camera:
          id:                              44ed7e1913a847b3b8d9884b9b02fb03
          sensor_type:                     CAMERA
          description:                     "Forward Down"
          topic:                           /alphasense/cam1
          line-delay-nanoseconds:          0
          image_height:                    1080
          image_width:                     1440
          type:                            pinhole
          intrinsics:
            rows:                          4
            cols:                          1
            data:
              - 696.7174426776
              - 696.4862496732
              - 708.4206218964
              - 535.6712007522
          distortion:
            type:                          equidistant
            parameters:
              rows:                        4
              cols:                        1
              data:
                - -0.0465180371
                - 0.0160363324
                - -0.0170339468
                - 0.0050095489
        T_B_C:
          rows:                            4
          cols:                            4
          data:
            - [-0.999947769741, -0.002969883895, -0.009779446770, 0.054037084732]
            - [0.009764748226, 0.004924013957, -0.999940200101, -0.079155584894]
            - [0.003017860428, -0.999983466801, -0.004894756606, -0.026252820103]
            - [0.000000000000, 0.000000000000, 0.000000000000, 1.000000000000]

      - camera:
          id:                              08faa68c87a84fd5bd1b0305c99b155d
          sensor_type:                     CAMERA
          description:                     "Upwards"
          topic:                           /alphasense/cam2
          line-delay-nanoseconds:          0
          image_height:                    1080
          image_width:                     1440
          type:                            pinhole
          intrinsics:
            rows:                          4
            cols:                          1
            data:
              - 702.3538912351
              - 702.1759854802
              - 718.7749348353
              - 535.2856167618
          distortion:
            type:                          equidistant
            parameters:
              rows:                        4
              cols:                        1
              data:
                - -0.0392852639
                - -0.0023244164
                - -0.0005553017
                - 0.0002238156
        T_B_C:
          rows:                            4
          cols:                            4
          data:
            - [0.014300546907, -0.999894900219, -0.002383877780, 0.000674266899]
            - [0.999889344876, 0.014290615401, 0.004132349859, -0.034911565484]
            - [-0.004097848469, -0.002442708854, 0.999988620341, 0.003681908458]
            - [0.000000000000, 0.000000000000, 0.000000000000, 1.000000000000]

      - camera:
          id:                              da7d19d6662f4a428240bf7f706bbb4d
          sensor_type:                     CAMERA
          description:                     "Right"
          topic:                           /alphasense/cam3
          line-delay-nanoseconds:          0
          image_height:                    1080
          image_width:                     1440
          type:                            pinhole
          intrinsics:
            rows:                          4
            cols:                          1
            data:
              - 703.2325755934
              - 703.2405654818
              - 703.0078028901
              - 537.7049174331
          distortion:
            type:                          equidistant
            parameters:
              rows:                        4
              cols:                        1
              data:
                - -0.041473724
                - 0.000366189
                - -0.0008241712
                - -0.0002216933
        T_B_C:
          rows:                            4
          cols:                            4
          data:
            - [-0.007315443787, 0.001874707327, -0.999971484470, -0.071180407892]
            - [-0.999967470673, -0.003411133669, 0.007309019364, -0.019610290592]
            - [-0.003397334126, 0.999992424791, 0.001899600300, -0.025381489017]
            - [0.000000000000, 0.000000000000, 0.000000000000, 1.000000000000]

      - camera:
          id:                              c70f9347314d4c26a72280c1f193b47d
          sensor_type:                     CAMERA
          description:                     "Left"
          topic:                           /alphasense/cam4
          line-delay-nanoseconds:          0
          image_height:                    1080
          image_width:                     1440
          type:                            pinhole
          intrinsics:
            rows:                          4
            cols:                          1
            data:
              - 701.4723842948
              - 701.6419154268
              - 700.4808652897
              - 541.8573746426
          distortion:
            type:                          equidistant
            parameters:
              rows:                        4
              cols:                        1
              data:
                - -0.0405675926
                - 0.0010964136
                - -0.0027765896
                - 0.0006435363
        T_B_C:
          rows:                            4
          cols:                            4
          data:
            - [-0.009729884445, -0.003198189286, 0.999947549091, 0.071856313376]
            - [-0.999939989667, -0.005003615651, -0.009745814239, -0.018677598863]
            - [0.005034522165, -0.999982367553, -0.003149312759, -0.025556027643]
            - [0.000000000000, 0.000000000000, 0.000000000000, 1.000000000000]

extrinsics:
  - sensor_id:                             bbf123479caf7592b35518478a2fe08d
    base_sensor_id:                        3da6d03bd42e41a93dc941bd5fd9353d
    T_B_S:
      rows:                                4
      cols:                                4
      data:
        - [-0.009512419028, 0.999954499995, -0.000715418261, 0.000054638802]
        - [-0.999954688116, -0.009512152479, 0.000375062393, -0.037469669768]
        - [0.000368240160, 0.000718953595, 0.999999673753, -0.126682785277]
        - [0.000000000000, 0.000000000000, 0.000000000000, 1.000000000000]

  - sensor_id:                             3da6d03bd42e41a93dc941bd5fd9353d
    base_sensor_id:                        3da6d03bd42e41a93dc941bd5fd9353d
    T_B_S:
      rows:                                4
      cols:                                4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]

  - sensor_id:                             acbb23479caf7592b35518478a2fe08f
    base_sensor_id:                        3da6d03bd42e41a93dc941bd5fd9353d
    T_B_S:
      rows:                                4
      cols:                                4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]

  - sensor_id:                             4af1bac2a7c5fad79f09e49e3b96d87c
    base_sensor_id:                        3da6d03bd42e41a93dc941bd5fd9353d
    T_B_S:
      rows:                                4
      cols:                                4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]
