sensors:
  - id:                                    5d2fcf479caf7592b35518478a2fe08f
    sensor_type:                           IMU
    description:                           "ADIS-16448 IMU"
    topic:                                 /VersaVIS/imu
    sigmas:
      gyro_noise_density:                  0.005
      gyro_bias_random_walk_noise_density: 4e-06
      acc_noise_density:                   0.01
      acc_bias_random_walk_noise_density:  0.0002
    saturation_accel_max_mps2:             150
    saturation_gyro_max_radps:             7.5
    gravity_magnitude_mps2:                9.808083883386614

  - id:                                    abf123479caf7592b35518478a2fe08f
    sensor_type:                           LIDAR
    description:                           "Lidarstick - Ouster OS1"
    topic:                                 /os1_cloud_node/points

  #- id:                                   ffff23479caf7592b35518478a2fe08f
    #sensor_type:                          POINTCLOUD_MAP
    #description:                          "Lidarstick - Ouster OS1 - Throttled"
    #topic:                                /os1_node/points_throttled

  - id:                                    aabb23479caf7592b35518478a2fe08f
    sensor_type:                           ODOMETRY_6DOF
    description:                           "ROVIOLI in Odometry mode"
    topic:                                 /odometry/maplab_odom_T_M_I

  - id:                                    8af1bac2a7c5fad79f09e49e3b96d87c
    sensor_type:                           NCAMERA
    description:                           "Lidarstick - Blackfly S 0.4MP (Color/Mono) Stereo Pair"
    topic:                                 ""
    cameras:
      - camera:
          id:                              ca17b5000f15adb3c0da8ac6b729ee05
          sensor_type:                     CAMERA
          description:                     "Blackfly S 0.4MP Color Camera"
          topic:                           /VersaVIS/cam0
          line-delay-nanoseconds:          0
          image_height:                    540
          image_width:                     720
          type:                            pinhole
          intrinsics:
            rows:                          4
            cols:                          1
            data:
              - 318.5615029627294
              - 318.5508828567644
              - 356.1322561401549
              - 280.2661824389335
          distortion:
            type:                          equidistant
            parameters:
              rows:                        4
              cols:                        1
              data:
                - 0.008389637685753994
                - -0.008026623555813853
                - 0.008468894266232789
                - -0.002661689249690012
        T_B_C:
          rows:                            4
          cols:                            4
          data:
            - [-0.9998799801805014, -0.006455918177665462, -0.01408354908125734, -0.03564392840560837]
            - [-0.01404346691982178, -0.006212441369011223, 0.9998820863527402, 0.04578551805201717]
            - [-0.006542650159741623, 0.9999598625408523, 0.006121032279554073, 0.05665531205066083]
            - [0, 0, 0, 1]


extrinsics:
  - sensor_id:                             abf123479caf7592b35518478a2fe08f
    base_sensor_id:                        5d2fcf479caf7592b35518478a2fe08f
    T_B_S:
      rows:                                4
      cols:                                4
      data:
        #- [-0.6978447576305695, 0.7161518144580716, 0.01180139381358678, -0.1021019447103219]
        #- [0.7160088243900917, 0.697942707663664, -0.01439931299167545, -0.08936602296234536]
        #- [-0.01854879087839803, -0.001598582974091693, -0.999826678424528, -0.07460082421278309]
        #- [0, 0, 0, 1]
        - [0.699172, -0.7149, 0.00870821, -0.100817]
        - [-0.714841, -0.699226, -0.00925541, -0.00368789]
        - [0.0127057, 0.000246142, -0.999919, -0.0998847]
        - [0, 0, 0, 1]

  - sensor_id:                             ffff23479caf7592b35518478a2fe08f
    base_sensor_id:                        5d2fcf479caf7592b35518478a2fe08f
    T_B_S:
      rows:                                4
      cols:                                4
      data:
        - [-0.6978447576305695, 0.7161518144580716, 0.01180139381358678, -0.1021019447103219]
        - [0.7160088243900917, 0.697942707663664, -0.01439931299167545, -0.08936602296234536]
        - [-0.01854879087839803, -0.001598582974091693, -0.999826678424528, -0.07460082421278309]
        - [0, 0, 0, 1]

  - sensor_id:                             5d2fcf479caf7592b35518478a2fe08f
    base_sensor_id:                        5d2fcf479caf7592b35518478a2fe08f
    T_B_S:
      rows:                                4
      cols:                                4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]

  - sensor_id:                             aabb23479caf7592b35518478a2fe08f
    base_sensor_id:                        5d2fcf479caf7592b35518478a2fe08f
    T_B_S:
      rows:                                4
      cols:                                4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]

  - sensor_id:                             8af1bac2a7c5fad79f09e49e3b96d87c
    base_sensor_id:                        5d2fcf479caf7592b35518478a2fe08f
    T_B_S:
      rows:                                4
      cols:                                4
      data:
        - [1,0,0,0]
        - [0,1,0,0]
        - [0,0,1,0]
        - [0,0,0,1]
